### ISSUE TITLE
Windows 2012R2 - undefined method 'InitialSize=' for nil:NilClass

### ISSUE THREAD

**Issue by snootched** [ptierno/puppet-windowspagefile#3] opened 2015-03-02 15:19 UTC
Running module on Windows 2012 R2 generates 'undefined method' error.

Module version: `mod 'ptierno/windowspagefile', '1.2.2'`

Attemtping code:

    class profiles::common::win::pagefile {
      pagefile { 'c:\pagefile.sys':
        initialsize => 200,
        maximumsize => 1024,
     }

      pagefile { 'u:\pagefile.sys':
        systemmanaged => true,
      }
}

    PS C:\temp> puppet resource pagefile
    pagefile { 'c:\pagefile.sys':
      ensure        => 'present',
      initialsize   => '200',
      maximumsize   => '1024',
      systemmanaged => 'false',
    }

    pagefile { 'u:\pagefile.sys':
      ensure        => 'present',
      initialsize   => '0',
      maximumsize   => '0',
      systemmanaged => 'true',
    }

Error observed:

    Error: Could not set 'present' on ensure: undefined method `InitialSize=' for nil:NilClass at 5:/etc/puppetlabs/puppet/environments/production/modules/profiles/manifests/common/win/pagefile.pp
    Error: Could not set 'present' on ensure: undefined method `InitialSize=' for nil:NilClass at 5:/etc/puppetlabs/puppet/environments/production/modules/profiles/manifests/common/win/pagefile.pp
    Wrapped exception:
    undefined method `InitialSize=' for nil:NilClass
    Error: /Stage[main]/Profiles::Common::Win::Pagefile/Pagefile[c:\pagefile.sys]/ensure: change from absent to present failed: Could not set 'present' on ensure: undefined method `InitialSize=' for nil:NilClass at 5:/etc/puppetlabs/puppet/environments/production/modules/profiles/manifests/common/win/pagefile.pp
    Error: Could not set 'present' on ensure: undefined method `InitialSize=' for nil:NilClass at 9:/etc/puppetlabs/puppet/environments/production/modules/profiles/manifests/common/win/pagefile.pp
    Error: Could not set 'present' on ensure: undefined method `InitialSize=' for nil:NilClass at 9:/etc/puppetlabs/puppet/environments/production/modules/profiles/manifests/common/win/pagefile.pp
    Wrapped exception:
    undefined method `InitialSize=' for nil:NilClass
    Error: /Stage[main]/Profiles::Common::Win::Pagefile/Pagefile[u:\pagefile.sys]/ensure: change from absent to present failed: Could not set 'present' on ensure: undefined method `InitialSize=' for nil:NilClass at 9:/etc/puppetlabs/puppet/environments/production/modules/profiles/manifests/common/win/pagefile.pp
    Notice: Finished catalog run in 7.03 seconds

**Comment by ptierno** [comment] 2015-03-02 15:33
Thank you for reporting this. When I have some free time I will try to duplicate these errors and work on a solution.

**Comment by ptierno** [comment] 2015-03-02 17:20
@snootched 

So far I am unable to duplicate this issue. Applying the following to a newly provisioned `Windows 2012 R2` box results in a successful puppet run.

    pagefile { 'c:\pagefile.sys':
      initialsize        => 200,
      maximumsize => 1024
    }
    pagefile { 'u:\pagefile.sys':
      systemmanaged => true
    }

After successful puppet run:

    PS C:\Program Files\Puppet Labs\Puppet Enterprise\bin> puppet resource pagefile
    pagefile { 'C:\pagefile.sys':
      ensure        => 'present',
      initialsize   => '200',
      maximumsize   => '1024',
      systemmanaged => 'false',
    }
    pagefile { 'U:\pagefile.sys':
      ensure        => 'present',
      initialsize   => '0',
      maximumsize   => '0',
      systemmanaged => 'true',
    }

Are using open source puppet or puppet enterprise? If you are using open source, what version of ruby are you running?

I have had similar issues on 2012 R2 before releasing version 1.2.2 where `win32ole` was returning lowercase drive letters when looking for existing page files while the puppet type was munging the path parameter to a capitalized drive letter. This was fixed in release 1.2.2 by downcasing the path parameter in the type based off of the `operatingsystemrelease` fact.

**Comment by snootched** [comment] 2015-03-02 20:32
@ptierno 
Thanks for looking into this.  We are running Puppet Enterprise 3.7.2
I wonder if this is a case issue on the drive letter.  After your successful run - I see your drive letters are uppercase when running "puppet resource pagefile" however, when I run that command, the drive letters are lower-case (mind you, the puppet agent didn't do a succesful run.)

**Comment by ptierno** [comment] 2015-03-02 22:12
@snootched 
That is strange. When I have time I'm going to install a fresh 2012 R2. I've been testing with a cloud image. Let me see if there is a difference. The case of the drive letters seem to be the issue here although im not sure why. I'll get back to you.

**Comment by ptierno** [comment] 2015-05-06 20:44
@snootched Still experiencing this issue? I am still unable to reproduce

**Comment by velocity303** [comment] 2015-05-26 17:42
Just commenting as I myself have just ran into this issue as well. If it helps, I also get a lowercase letter returned when issuing the puppet resource command on Server 2012 R2.

**Comment by velocity303** [comment] 2015-05-26 18:01
I was actually able to get around the issue and everything worked normally after manually changing the pagefile to be system managed before an additional puppet run. This may be an issue that occurs due to how the pagefile was previously set.

For reference my initial page file was set as follows: 

Custom Size: 
initial size 512MB
maximum size 512MB
Selected Drive C:

Automatically manage paging file size for all drives was disabled.

Hope this helps!

**Comment by ptierno** [comment] 2015-07-09 03:00
@velocity303 @snootched I believe II have found the issue. A commit should be coming shortly after doing some testing.

**Comment by TheCraiggers** [comment] 2015-08-03 14:27
For what it's worth, I'm also running into this issue with Puppet Enterprise 3.8 with a pp similar to @snootched. 

I know you said you believe you already found the issue, but let me know if I can do anything to help diagnose / test.

**Comment by ptierno** [comment] 2015-08-03 14:50
@TheCraiggers apologies for the delay. I have been strapped on time. I will try to get a commit in between today and tomorrow on a new branch for you to test.

**Comment by ptierno** [comment] 2015-08-05 02:10
@TheCraiggers @snootched @velocity303 

Please test now against the `github_issue_3` branch

**Comment by TheCraiggers** [comment] 2015-08-05 17:23
Well, the good news is it looks to have fixed the errors I was seeing. The bad news is the test I was attempting to do is still failing.

I'm attempting to add a new pagefile on another drive, and remove the default one on C:. So I have a init.pp that looks like this:

                #Remove pagefile from the C drive
                pagefile { 'c:\pagefile.sys':
                    ensure => absent,
                }

                #Add pagefile to the E drive
                pagefile { 'e:\pagefile.sys':
                    ensure => present,
                    systemmanaged => true,
                }

It seems to add the pagefile just fine to the E drive, but it's not removing the pagefile from C. At least not consistently.

I noticed the following in the ruby code (I'm by no means a ruby expert though) which looks to be hard coding the pagefile to be 'present'. Is this intended? Should I be attempting to go about this a different way? Should I open a new issue?

    new(
        :name          => pagefile.Name,
        :ensure        => :present,
        :initialsize   => pagefile.InitialSize,
        :maximumsize   => pagefile.MaximumSize,
        :systemmanaged => system_managed
      )

**Comment by ptierno** [comment] 2015-08-05 17:31
@TheCraiggers that code is part of the `self.instances` method which is used by the `puppet resource` command, shouldn't have much to do with a puppet run. This issue may be related to how i handled `ensure => absent`. I think it turns on windows automatic managed pagefile setting. can you give me the output of `puppet resource pagefile` from your windows machine?

Thanks

**Comment by TheCraiggers** [comment] 2015-08-05 19:43
```puppet
pagefile { 'C:\pagefile.sys':
  ensure        => 'present',
  initialsize   => '0',
  maximumsize   => '0',
  systemmanaged => 'true',
}
pagefile { 'e:\pagefile.sys':
  ensure        => 'present',
  initialsize   => '0',
  maximumsize   => '0',
  systemmanaged => 'true',
}
```

**Comment by ptierno** [comment] 2015-08-05 20:41
@TheCraiggers thats because the 'automatically managed' setting was enabled. I'm going to mark this issue as closed. Can you create a new issue regarding this and I will  work to add the expected functionality to `ensure`, or at least create a new parameter on how absent should work, either restore the default windows automatic management, or completely remove.

**Closed** 2015-08-05 20:41 UTC
